### ISSUE TITLE
data.txt missing

### ISSUE THREAD

**Issue by BaumGuard** [stdevPavelmc/FAASGS#14]
Hi,
I've installed FAASGS, the corresponding dependencies and a web server on my Raspberry Pi 3. I had some trouble with sats.sh and followed the steps in the other issue. I created the file /root/.predict/predict.qth and executed `/usr/bin/predict -t /etc/sat_data/data.txt -p NOAA19`. Then it shows the following error message:
`*** ERROR!  Your TLE file "/etc/sat_data/data.txt" could not be loaded!`
If I create a file called data.txt in /etc/sat_data, and run sats.sh once again, it shows some satellites but not the passes:
`Updating data and scheduling new sats
Can't fetch fresh TLE data, using old one
=> ISS (ZARYA)/ISS
=> RADFXSAT (FOX-1B)/AO91-FOX-1B
=> FOX-1CLIFF (AO-95)/AO95-FOX-1CLIFF
=> FOX-1D (AO-92)/AO92-FOX-1D
=> DIWATA-2B/PO101-DIWATA-2B
=> NOAA 19/NOAA19
=> NOAA 18/NOAA18
=> NOAA 15/NOAA15`

Thank you for your help in advance!

**Comment by stdevPavelmc** [comment]
Hi @BaumGuard !

Thanks for using the software

Did you edited the /etc/sat_data/user.conf file?

At the bottom of the file there is a proxy settings, if you don't use a proxy you need to clean that vars...

**Comment by BaumGuard** [comment]
Oh, sorry I forgot to change the proxy settings.
Now it shows the satellite passes as intended, but the web interface doesn't work. Do I have to move the files from ~/FAASGS/www to /var/www myself? When I copy the folder to that location and rename the folder to html and open the Pi's ip address in the browser, it says "403 Forbidden".

**Comment by stdevPavelmc** [comment]
Just run this commands on the FAASGS folder to fix that problems

```
rm cwww wwwt
make wwwt
make cwww
```

And just now I spotted a bug in the makefile... Fixing it ASAP

Please update (See README.MD section update)

**Comment by stdevPavelmc** [comment]
Done, Fixed

Go update and please please comment your results

**Comment by BaumGuard** [comment]
After running `make install` it shows the following error message:
`rm: removal of '/var/www/html/index.html' is not possible: File or directory not found
make: *** [Makefile:18: wwwt] Error 1`
The message was originally in German.

**Comment by stdevPavelmc** [comment]
That error was fixed on the last update.

Please follow instructions on the README.md and update [yes, again] and try it.

**Comment by BaumGuard** [comment]
The error still occurs and I've completely reinstalled FAASGS. Here are the commands I ran:
`sudo apt -y update && sudo apt -y upgrade && sudo apt -y install nginx php php-fpm predict git make aptitude jq`
`wget https://www.wxtoimgrestored.xyz/beta/wxtoimg-armhf-2.11.2-beta.deb && sudo dpkg -i wxtoimg-armhf-2.11.2-beta.deb && sudo aptitude install -f`
After running those commands, I entered my location, my coordinates and the altitude in xwxtoimg and copied .wxtoimgrc to /root.
To install FAASGS, I ran the following commands:
`git clone https://github.com/stdevPavelmc/FAASGS && cd FAASGS && sudo make install`
At the end of `sudo make install` the same error message from my last comment came again.

Does FAASGS has to be installed in /home/pi or in /root? Both ways lead to the same error in my case.

**Comment by stdevPavelmc** [comment]
You missed the edit of the user data in the file /etc/sat_data/user.conf

Run `sudo make clean ; sudo make install` after you customize the user.conf file

**Comment by BaumGuard** [comment]
I have now edited /root/FAASGS/sat_data/user.conf before installing FAASGS, but the error still occurred. I commented line 19 in the Makefile out, because there was no index.html obviously. After that the installation worked.

**Comment by stdevPavelmc** [comment]
Done, you was right

There was a bug, that rm statement https://github.com/stdevPavelmc/FAASGS/issues/14#issuecomment-774751613 was not getting captured and that's why the whole process stop.

It's fixed now.

Please re-read the README (I have fixed a few minor issues and updated the install & upgrade instructions), specially the upgrade process, follow it and you will be fine.

I wait for your feedback, cheers.

**Comment by BaumGuard** [comment]
Ok, it seems to work better now, although it still shows these two error messages at the end of `make install`:
`rm: the removal of '/var/www/html/index.html' is not possible: File or Directory not found
rm: the removal of '/usr/local/bin/sats.sh' is not possible: File or Directory not found`

I also have to create the folder `/root/.predict` and `/root/.predict/predict.qth` manually, because otherways I get this error message: `/usr/local/bin/sats.sh: line 89: [: file: integer expression expected`

When I open the ip address of my RPi, there's still the start page "Welcome to nginx!" and not the passes schedule.

**Comment by stdevPavelmc** [comment]
> Ok, it seems to work better now, although it still shows these two error messages at the end of `make install`:
> `rm: the removal of '/var/www/html/index.html' is not possible: File or Directory not found rm: the removal of '/usr/local/bin/sats.sh' is not possible: File or Directory not found`
> 
> I also have to create the folder `/root/.predict` and `/root/.predict/predict.qth` manually, because otherways I get this error message: `/usr/local/bin/sats.sh: line 89: [: file: integer expression expected`
> 
> When I open the ip address of my RPi, there's still the start page "Welcome to nginx!" and not the passes schedule.

Please follow the update procedure described in the README.md file or erase the FAASGS folder and start over.

I have submitted a patch that fixed that error you are seeing:

`rm: the removal of '/var/www/html/index.html' is not possible: File or Directory not found rm: the removal of '/usr/local/bin/sats.sh' is not possible: File or Directory not found`

**Comment by BaumGuard** [comment]
Yesterday, I installed FAASGS from new. So it should be the latest version. If I follow the instructions for the update procedure, it says that there's nothing to update.

But now that it seems to work from the terminal, we should try to get the webpage working. As mentioned in one of my previous posts, I installed nginx, php and php-fpm by running `sudo apt install nginx php php-fpm`. Is that already enough?

**Comment by stdevPavelmc** [comment]
> Yesterday, I installed FAASGS from new. So it should be the latest version. If I follow the instructions for the update procedure, it says that there's nothing to update.
> 
> But now that it seems to work from the terminal, we should try to get the webpage working. As mentioned in one of my previous posts, I installed nginx, php and php-fpm by running `sudo apt install nginx php php-fpm`. Is that already enough?

Yes, a `sudo apt install nginx php php-fpm` must be enough.

I'm waiting to see if it works now. keep me posted on the progress

**Comment by BaumGuard** [comment]
No, it still doesn't work. Does it matter, whether I install php or nginx first?

**Comment by BaumGuard** [comment]
Apparently, the installing order makes no difference. I still have the problem, that there is no pass list when I open the ip address of my RPi.

**Comment by BaumGuard** [comment]
Hi Pavel,
the website is still not working. When can you help me?

**Comment by stdevPavelmc** [comment]
Hi @BaumGuard, patience please.

This is a hobby project, and I have a daily work to fill.

I have triaged a few bugs and will address it over the weekend, I will notify here on the issues to the affected users that it's respective bugs are solved and instructions on how to test it. 

> Hi Pavel,
> the website is still not working. When can you help me?
